services:
  - type: web
    name: alumni-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://anushka:anushka11@alumni.w9d64fs.mongodb.net/
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://alumni-portal.netlify.app
  - type: web
    name: alumni-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://alumni-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: alumni-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://anushka:anushka11@alumni.w9d64fs.mongodb.net/
      - key: JWT_SECRET
        value: alumni_portal_secret_key
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://alumni-7bn6.onrender.com 